___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print("Версія NumPy:", np.__version__)
print("\nКонфігурація NumPy:")
np.show_config()

Версія NumPy: 1.21.5

Конфігурація NumPy:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/temak/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/temak/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/temak/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/temak/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/temak/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/temak/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/temak/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/temak/anaconda3\\Library\\include']
Supported 

Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
vector = np.ones(10)
print(vector)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [4]:
vector = np.arange(11)
print(vector)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [5]:
matrix = np.zeros((5, 5))
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [7]:
vector = np.random.randint(0, 10, 20)
nonzero_indexes = np.nonzero(vector)

print("Вектор з випадковими цілими числами:")
print(vector, "\n")
print("Індекси ненульових елементів:")
print(nonzero_indexes)

Вектор з випадковими цілими числами:
[0 2 4 0 8 3 8 4 7 6 6 5 0 0 4 2 9 0 7 0] 

Індекси ненульових елементів:
(array([ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 14, 15, 16, 18],
      dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [8]:
print("Вектор з випадковими цілими числами:")
print(vector)
print("Середнє значення:", np.mean(vector))
print("Медіана:", np.median(vector))
print("Стандартне відхилення:", np.std(vector))

Вектор з випадковими цілими числами:
[0 2 4 0 8 3 8 4 7 6 6 5 0 0 4 2 9 0 7 0]
Середнє значення: 3.75
Медіана: 4.0
Стандартне відхилення: 3.0639027399707057


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [18]:
matrix1 = np.random.randint(9, size=(4, 2))
matrix2 = np.random.randint(9, size=(2, 2))
result = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Результат перемноження:")
print(result)

Матриця 1:
[[6 5]
 [2 3]
 [2 4]
 [4 1]]
Матриця 2:
[[2 5]
 [4 1]]
Результат перемноження:
[[32 35]
 [16 13]
 [20 14]
 [12 21]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [19]:
minimum = np.min(result)
maximum = np.max(result)

max_index = np.argmax(result)
result[max_index] = 0

print("Результуючий вектор:")
print(result)
print("Мінімальне значення:", minimum)
print("Максимальне значення:", maximum)

Результуючий вектор:
[[32 35]
 [ 0  0]
 [20 14]
 [12 21]]
Мінімальне значення: 12
Максимальне значення: 35


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [20]:
corr = np.corrcoef(result)
corr_first_row = corr[0, 1:]
print(corr_first_row)

[nan -1.  1.]


C:\Users\temak\anaconda3\lib\site-packages\numpy\lib\function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
C:\Users\temak\anaconda3\lib\site-packages\numpy\lib\function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


Дано матрицю. Знайти ранг матриці:

In [22]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

print(np.linalg.matrix_rank(a))

3


Знайти визначник матриці:

In [24]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [26]:
eig_values, eig_vectors = np.linalg.eig(a)

print("Власні значення матриці a:", eig_values)
print("Власні вектори матриці a:", eig_vectors)

Власні значення матриці a: [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
Власні вектори матриці a: [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [32]:
a = np.random.randint(0,10,50)
a

array([4, 5, 0, 8, 4, 0, 7, 1, 9, 6, 6, 6, 6, 1, 2, 7, 5, 1, 9, 2, 7, 9,
       5, 1, 1, 2, 8, 7, 1, 2, 7, 1, 4, 8, 8, 4, 6, 2, 2, 8, 4, 9, 6, 3,
       5, 1, 1, 3, 1, 3])

In [33]:
np.argmax(np.bincount(a))

1

Виведіть лише парні числа, що діляться на 5:

In [45]:
a = np.random.randint(0,50,50)
a

array([15, 34, 38, 18, 14, 13, 32, 35, 18, 11, 46, 30,  9,  4, 41, 26, 25,
       17, 29, 21,  8, 11,  6,  9,  8, 47, 14, 35, 29, 10,  6, 17,  7, 46,
       48, 47, 31, 29, 31,  7, 25,  1, 25, 33, 13, 16, 19,  4, 48, 32])

In [46]:
for num in a:
    if num % 2 == 0 and num % 5 == 0 and num != 0:
        print(num)

30
10


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [51]:
A = np.array([[2, 5], [1, -10]])
B = np.array([1, 3])

X = np.linalg.solve(A, B)
X

array([ 1. , -0.2])